/* SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause */
/*
 * Copyright (c) 2018-2020, The Linux Foundation. All rights reserved.
 */

#ifndef __DT_BINDINGS_MAILBOX_IPCC_H
#define __DT_BINDINGS_MAILBOX_IPCC_H

/* Signal IDs for MPROC protocol */
#define IPCC_MPROC_SIGNAL_GLINK_QMP	0
#define IPCC_MPROC_SIGNAL_TZ		1
#define IPCC_MPROC_SIGNAL_SMP2P		2
#define IPCC_MPROC_SIGNAL_PING		3

/* Client IDs */
#define IPCC_CLIENT_AOP			0
#define IPCC_CLIENT_TZ			1
#define IPCC_CLIENT_MPSS		2
#define IPCC_CLIENT_LPASS		3
#define IPCC_CLIENT_SLPI		4
#define IPCC_CLIENT_SDC			5
#define IPCC_CLIENT_CDSP		6
#define IPCC_CLIENT_NPU			7
#define IPCC_CLIENT_APSS		8
#define IPCC_CLIENT_GPU			9
#define IPCC_CLIENT_CVP			10
#define IPCC_CLIENT_CAM			11
#define IPCC_CLIENT_VPU			12
#define IPCC_CLIENT_PCIE0		13
#define IPCC_CLIENT_PCIE1		14
#define IPCC_CLIENT_PCIE2		15
#define IPCC_CLIENT_SPSS		16
#define IPCC_CLIENT_NSP1		18
#define IPCC_CLIENT_TME			23
#define IPCC_CLIENT_WPSS		24
#define IPCC_CLIENT_GPDSP0		31
#define IPCC_CLIENT_GPDSP1		32

/* Platform specific physical client IDs */

/* Glymur physical client IDs */
#define GLYMUR_MPROC_AOP		0
#define GLYMUR_MPROC_TZ			1
#define GLYMUR_MPROC_MPSS		2
#define GLYMUR_MPROC_LPASS		3
#define GLYMUR_MPROC_SLPI		4
#define GLYMUR_MPROC_SDC		5
#define GLYMUR_MPROC_CDSP		6
#define GLYMUR_MPROC_NPU		7
#define GLYMUR_MPROC_APSS		8
#define GLYMUR_MPROC_GPU		9
#define GLYMUR_MPROC_ICP		11
#define GLYMUR_MPROC_VPU		12
#define GLYMUR_MPROC_PCIE0		13
#define GLYMUR_MPROC_PCIE1		14
#define GLYMUR_MPROC_PCIE2		15
#define GLYMUR_MPROC_SPSS		16
#define GLYMUR_MPROC_PCIE3		19
#define GLYMUR_MPROC_PCIE4		20
#define GLYMUR_MPROC_PCIE5		21
#define GLYMUR_MPROC_PCIE6		22
#define GLYMUR_MPROC_TME		23
#define GLYMUR_MPROC_WPSS		24
#define GLYMUR_MPROC_PCIE7		44
#define GLYMUR_MPROC_SOCCP		46

#define GLYMUR_COMPUTE_L0_LPASS		0
#define GLYMUR_COMPUTE_L0_CDSP		1
#define GLYMUR_COMPUTE_L0_APSS		2
#define GLYMUR_COMPUTE_L0_GPU		3
#define GLYMUR_COMPUTE_L0_CVP		6
#define GLYMUR_COMPUTE_L0_ICP		7
#define GLYMUR_COMPUTE_L0_VPU		8
#define GLYMUR_COMPUTE_L0_DPU		9
#define GLYMUR_COMPUTE_L0_SOCCP		11

#define GLYMUR_COMPUTE_L1_LPASS		0
#define GLYMUR_COMPUTE_L1_CDSP		1
#define GLYMUR_COMPUTE_L1_APSS		2
#define GLYMUR_COMPUTE_L1_GPU		3
#define GLYMUR_COMPUTE_L1_CVP		6
#define GLYMUR_COMPUTE_L1_ICP		7
#define GLYMUR_COMPUTE_L1_VPU		8
#define GLYMUR_COMPUTE_L1_DPU		9
#define GLYMUR_COMPUTE_L1_SOCCP		11

#define GLYMUR_PERIPH_LPASS		0
#define GLYMUR_PERIPH_APSS		1
#define GLYMUR_PERIPH_PCIE0		2
#define GLYMUR_PERIPH_PCIE1		3
#define GLYMUR_PERIPH_PCIE2		6
#define GLYMUR_PERIPH_PCIE3		7
#define GLYMUR_PERIPH_PCIE4		8
#define GLYMUR_PERIPH_PCIE5		9
#define GLYMUR_PERIPH_PCIE6		10
#define GLYMUR_PERIPH_PCIE7		11
#define GLYMUR_PERIPH_SOCCP		13
#define GLYMUR_PERIPH_WPSS		16

#endif
