# SPDX-License-Identifier: GPL-2.0



subdir-ccflags-y += -DDBG_ENABLE

#obj-$(CONFIG_DEVAPC_ARCH_COMMON) += device-apc-common-legacy.o
#device-apc-common-legacy-$(CONFIG_DEVAPC_ARCH_COMMON) += devapc-mtk-common.o

obj-y += devapc-mtk-multi-ao.o

obj-y += devapc-mt6991.o
