# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_SND_SOC_CDNS_I2S_MC) += snd-soc-cdns-i2s-mc.o
snd-soc-cdns-i2s-mc-y := cdns_i2s_mc.o

obj-$(CONFIG_SND_SOC_CDNS_I2S_SC) += snd-soc-cdns-i2s-sc.o
snd-soc-cdns-i2s-sc-y := cdns_i2s_sc.o

obj-$(CONFIG_SND_SOC_SKY1_SOUND_CARD) += snd-soc-sky1-card.o
snd-soc-sky1-card-y := sky1-card.o card-utils.o
