ccflags-y += -I$(src) -I$(src)/if -I$(src)/dev -I$(src)/if/v4l2 -I$(src)/external
ccflags-$(CONFIG_VIDEO_LINLON_FTRACE) += -DMVX_LOG_FTRACE_ENABLE
ccflags-$(CONFIG_VIDEO_LINLON_PRINT_FILE) += -DMVX_LOG_PRINT_FILE_ENABLE
ccflags-$(CONFIG_VIDEO_LINLON_ANDROID_KERNEL) += -DMVX_ANDROID_KERNEL
ccflags-y += $(EXTRA_CCFLAGS)

obj-$(CONFIG_VIDEO_LINLON) := amvx.o

if-y := if/mvx_if.o \
	if/mvx_buffer.o \
	if/mvx_firmware_cache.o \
	if/mvx_firmware.o \
	if/mvx_firmware_v2.o \
	if/mvx_firmware_v3.o \
	if/mvx_mmu.o \
	if/mvx_secure.o \
	if/mvx_session.o

if-y += if/v4l2/mvx_ext_v4l2.o \
	if/v4l2/mvx_v4l2_buffer.o \
	if/v4l2/mvx_v4l2_session.o \
	if/v4l2/mvx_v4l2_vidioc.o \
	if/v4l2/mvx_v4l2_fops.o \
	if/v4l2/mvx_v4l2_ctrls.o

dev-y := dev/mvx_dev.o \
	 dev/mvx_hwreg.o \
	 dev/mvx_hwreg_v500.o \
	 dev/mvx_hwreg_v550.o \
	 dev/mvx_hwreg_v61.o \
	 dev/mvx_hwreg_v52_v76.o \
	 dev/mvx_lsid.o \
	 dev/mvx_scheduler.o \
	 mvx_pm_runtime.o

dev-$(CONFIG_PLAT_DSM_SYSEVENT) += dev/mvx_dsm.o

amvx-y := mvx_driver.o \
	  mvx_seq.o \
	  mvx_log.o \
	  mvx_log_group.o \
	  $(if-y) $(dev-y)
